from __future__ import annotations

import json
from pathlib import Path

import pytest

from hakoniwa_pdu_ros.service_binding import load_service_binding, service_key
from hakoniwa_pdu_ros.service_config_generator import (
    generate_service_configs,
    resolve_offset_size,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
BINDING = REPO_ROOT / "config" / "service" / "add_two_ints.json"
FIXTURES = REPO_ROOT / "test" / "fixtures"
OFFSETS = FIXTURES / "offset"


def test_load_add_two_ints_service_binding() -> None:
    config = load_service_binding(BINDING)

    assert config.version == 1
    assert config.service.transport_config.name == "add_two_ints-transport.json"
    assert len(config.bindings) == 1
    binding = config.bindings[0]
    assert binding.client_endpoint.node_id == "hakoniwa-pdu-ros-service"
    assert binding.server_endpoint.node_id == "server_node"
    assert binding.ros_type == "example_interfaces/srv/AddTwoInts"
    assert binding.max_clients == 4
    assert binding.heap.request_bytes == 0
    assert binding.heap.response_bytes == 0


def test_generate_add_two_ints_server_and_client_configs(tmp_path: Path) -> None:
    resolved_ros_types = []

    generated = generate_service_configs(
        BINDING,
        output_dir=tmp_path,
        offset_dir=OFFSETS,
        ros_interface_resolver=resolved_ros_types.append,
        pdu_type_resolver=lambda _ros_type, _override: "hako_srv_msgs/AddTwoInts",
        rpc_generator=_fake_rpc_generator,
    )

    assert resolved_ros_types == ["example_interfaces/srv/AddTwoInts"]
    assert len(generated.services) == 1
    assert generated.services[0].pdu_service_type == "hako_srv_msgs/AddTwoInts"
    manifest = _load(generated.manifest)
    assert manifest["services"][0] == {
        "name": "Service/Add",
        "type": "hako_srv_msgs/AddTwoInts",
        "maxClients": 4,
        "clientNamePrefix": "hakoniwa_pdu_ros_add",
        "packetSize": {"requestBaseSize": 296, "responseBaseSize": 288},
        "bufferHeap": {"requestSize": 0, "responseSize": 0},
        "clientEndpoint": {"nodeId": "hakoniwa-pdu-ros-service"},
        "serverEndpoint": {"nodeId": "server_node"},
    }
    assert manifest["transport"]["endpoints"]["server_node"]["role"] == "server"


def test_generation_is_idempotent(tmp_path: Path) -> None:
    kwargs = {
        "output_dir": tmp_path,
        "offset_dir": OFFSETS,
        "ros_interface_resolver": lambda _ros_type: None,
        "pdu_type_resolver": lambda _ros_type, _override: "hako_srv_msgs/AddTwoInts",
        "rpc_generator": _fake_rpc_generator,
    }
    first = generate_service_configs(BINDING, **kwargs)
    first_server = first.server_config.read_bytes()
    first_client = first.client_config.read_bytes()

    second = generate_service_configs(BINDING, **kwargs)

    assert second.server_config.read_bytes() == first_server
    assert second.client_config.read_bytes() == first_client
    assert not list(tmp_path.glob("*.tmp"))


def test_default_output_uses_cwd_and_binding_stem(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    generated = generate_service_configs(
        BINDING,
        offset_dir=OFFSETS,
        ros_interface_resolver=lambda _ros_type: None,
        pdu_type_resolver=lambda _ros_type, _override: "hako_srv_msgs/AddTwoInts",
        rpc_generator=_fake_rpc_generator,
    )

    assert generated.output_dir == (
        tmp_path / "build" / "generated" / "service" / "add_two_ints"
    )


def test_offset_sizes_match_existing_add_two_ints_contract() -> None:
    assert resolve_offset_size(OFFSETS, "hako_srv_msgs/AddTwoIntsRequestPacket") == 296
    assert resolve_offset_size(OFFSETS, "hako_srv_msgs/AddTwoIntsResponsePacket") == 288


def test_heap_mapping_and_channel_ids_are_scoped_per_service(tmp_path: Path) -> None:
    config_path = _copy_binding(tmp_path)
    data = _load(config_path)
    first = data["bindings"][0]
    first["max_clients"] = 1
    first["heap"] = {"request_bytes": 64, "response_bytes": 128}
    second = json.loads(json.dumps(first))
    second["ros_name"] = "/subtract_two_ints"
    second["hakoniwa_service"] = "Service/Subtract"
    data["bindings"].append(second)
    _write(config_path, data)

    generated = generate_service_configs(
        config_path,
        output_dir=tmp_path / "generated",
        offset_dir=OFFSETS,
        ros_interface_resolver=lambda _ros_type: None,
        pdu_type_resolver=lambda _ros_type, _override: "hako_srv_msgs/AddTwoInts",
        rpc_generator=_fake_rpc_generator,
    )
    services = _load(generated.manifest)["services"]

    assert services[0]["bufferHeap"] == {
        "requestSize": 64,
        "responseSize": 128,
    }
    assert services[1]["bufferHeap"] == {
        "requestSize": 64,
        "responseSize": 128,
    }
    # Channel IDs are deliberately absent from the ROS adapter output. They
    # are owned and generated by hakoniwa-pdu-rpc.
    assert all("clients" not in service for service in services)


def test_service_key_uses_hakoniwa_service_tail() -> None:
    assert service_key("Service/AddTwoInts") == "add_two_ints"


@pytest.mark.parametrize(
    ("field", "value", "message"),
    [
        ("max_clients", 0, "max_clients must be a positive integer"),
        ("timeout_msec", True, "timeout_msec must be a positive integer"),
    ],
)
def test_binding_rejects_invalid_positive_integer(
    tmp_path: Path, field: str, value: object, message: str
) -> None:
    config_path = _copy_binding(tmp_path)
    data = _load(config_path)
    data["bindings"][0][field] = value
    _write(config_path, data)

    with pytest.raises(ValueError, match=message):
        load_service_binding(config_path)


def test_binding_rejects_unknown_field(tmp_path: Path) -> None:
    config_path = _copy_binding(tmp_path)
    data = _load(config_path)
    data["bindings"][0]["rpc_client_names"] = ["must-not-be-user-input"]
    _write(config_path, data)

    with pytest.raises(ValueError, match="Unsupported bindings\\[0\\] fields"):
        load_service_binding(config_path)


def test_binding_rejects_kind_field(tmp_path: Path) -> None:
    config_path = _copy_binding(tmp_path)
    data = _load(config_path)
    data["kind"] = "ros_service_server"
    _write(config_path, data)

    with pytest.raises(ValueError, match="Unsupported root fields: kind"):
        load_service_binding(config_path)


def test_binding_rejects_missing_endpoint_reference(tmp_path: Path) -> None:
    config_path = _copy_binding(tmp_path)
    transport_path = tmp_path / "add_two_ints-transport.json"
    transport = _load(transport_path)
    del transport["endpoints"]["hakoniwa-pdu-ros-service"]
    _write(transport_path, transport)

    with pytest.raises(ValueError, match="missing referenced node IDs"):
        load_service_binding(config_path)


def _copy_binding(tmp_path: Path) -> Path:
    config_path = tmp_path / "binding.json"
    transport_path = tmp_path / "add_two_ints-transport.json"
    config_path.write_text(BINDING.read_text(encoding="utf-8"), encoding="utf-8")
    transport_path.write_text(
        (BINDING.parent / "add_two_ints-transport.json").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    return config_path


def _fake_rpc_generator(manifest_path: Path, output_dir: Path) -> list[Path]:
    # Unit tests here verify only the ROS-to-RPC manifest adapter. Native
    # configuration expansion has its own contract tests in hakoniwa-pdu-rpc.
    manifest = _load(manifest_path)
    generated = []
    for name, value in (
        ("rpc-server-services.json", {"services": manifest["services"]}),
        ("rpc-client-services.json", {"services": manifest["services"]}),
        ("endpoints.json", []),
    ):
        path = output_dir / name
        path.write_text(json.dumps(value, sort_keys=True), encoding="utf-8")
        generated.append(path)
    return generated


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data), encoding="utf-8")
